server:
  port: 8081

  # 인코딩을 위한 설정
  servlet:
    encoding:
      charset: utf-8
      force-response: true

spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
      username: hr
      password: hr


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1056152786225-ssoboempquap25h5h6hghcsp21tk5n7j.apps.googleusercontent.com
#            client-id: 227302417113-j672tg79f1mtdj8rarrrk829ig15rq4a.apps.googleusercontent.com
            client-secret: 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
#            client-secret: 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
#            redirect-uri: http://localhost:8081/login/oauth2/code/google
            client-name: kkiri-google
            redirect-uri: http://localhost:3000/auth/google
            scope: profile,email

          naver:
            client-id: TmC2zgdKuyI4RA4R8qta
#            client-id: voa6ErTaNMtmcKMrC2VE
            client-secret: sKgaWD5MMq
#            client-secret: 9wyMXiX4zn
            authorization-grant-type: authorization_code
            client-name: kkiri-naver
            redirect-uri: http://localhost:3000/auth/naver

          kakao:
            client-id: 589c5b3cc0bf60c60e8185acda5bfed7
#            client-id: d17ae8b9f4f682aaba42421ce469dd76
            client-secret: Wv3VHLNCX8HM3LbmqwaeTnRrMUUb1yJ5
#            client-secret: 8UKeCB2FmJmu7q9kVrwGEGKxqae9XmLH
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: kkiri-kakao
            redirect-uri: http://localhost:3000/auth/kakao
            scope: profile_nickname,account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF #SQL만 로그로 남긴다.
      sqltiming: INFO #SQL과 소요시간을 표기한다.
      connection : OFF # 커넥션 확인가능
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret:
    ZnBwMmltV1pzWnI4bFpvV0Z3SGFnTEN4M1o0Znlrd2l2dFJ6dXltVG8wVXJoQ2taUEFzMXZJaXhkQ3c2cWFLdw==
#    fpp2imWZsZr8lZoWFwHagLCx3Z4fykwivtRzuymTo0UrhCkZPAs1vIixdCw6qaKw