server:
  port: 8081

spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@localhost:1521:XE
      username: hr
      password: hr

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1056152786225-ssoboempquap25h5h6hghcsp21tk5n7j.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-id: TmC2zgdKuyI4RA4R8qta
            client-secret: sKgaWD5MMq
            authorization-grant-type: authorization_code
            client-name: client-naver
            redirect-uri: http://localhost:3000

          kakao:
            client-id: 589c5b3cc0bf60c60e8185acda5bfed7
            client-secret: 975908
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            client-name: client-kakao
            redirect-uri: http://localhost:3000
            scope:
              - profile_nickname
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json
            user-name-attribute: kakao_account

# log4jdbc, Mybatis Console Log
logging:
  level:
    com:
      zaxxer:
        hikari: INFO
    javax:
      sql:
        DataSource: OFF
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF #SQL만 로그로 남긴다.
      sqltiming: INFO #SQL과 소요시간을 표기한다.
      connection : OFF # 커넥션 확인가능
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  secret:
    Victory awaits him who has everything in order, luck, people call it. Defeat is certain for him who has neglected to take the necessary precautions in time, this is called bad luck.